package com.bbva.devicelib.emv.outputData.enums.tvr

enum class ETvrDescriptor(val value: String) {
    B1_b8("OFFLINE DATA AUTHENTICATION"),
    B1_b7("SDA Failed"),
    B1_b6("ICC DATA"),
    B1_b5("CARD APPEARS"),
    B1_b4("DDA FAILED"),
    B1_b3("CDA FAILED"),
    B1_b2("SDA selected"),
    B1_b1("RFU"),

    B2_b8("ICC DIFERENT APP_VERSION"),
    B2_b7("EXPIRED APPLICATION"),
    B2_b6("APP NO YET EFECTIVE"),
    B2_b5("SERVICE NOT ALLOWED FOR CARD"),
    B2_b4("NEW CARD"),
    B2_b3("RFU"),
    B2_b2("RFU"),
    B2_b1("RFU"),

    B3_b8("CARDHOLDER VERIFICATION"),
    B3_b7("UNRECOGNIZED CVM"),
    B3_b6("PIN TRY LIMIT EXCEEDED"),
    B3_b5("PIN ENTRY REQ PIN. PAD NO PRESENT"),
    B3_b4("PIN ENTRY REQ PIN. PAD PRESENT NO ENTERED"),
    B3_b3("ONLINE PIN ENTERED"),
    B3_b2("RFU"),
    B3_b1("RFU"),

    B4_b8("TRANSACT EXCEED FLOOR LIMIT"),
    B4_b7("LOWER CONSECUTIVE OFFLINE LIMIT EXCEED"),
    B4_b6("UPPER CONSECUTIVE OFFLINE LIMIT EXCEED"),
    B4_b5("TRANSACT SELECTED RADOMLY FOR ONLINE PROC"),
    B4_b4("MERCHANT FORCED TRANS ONLINE"),
    B4_b3("RFU"),
    B4_b2("RFU"),
    B4_b1("RFU"),

    B5_b8("DEFAULT TDOL USED"),
    B5_b7("ISSUER AUTHENTICATION FAILED"),
    B5_b6("SCRIPT PROCESSING FAILED BEFORE FINAL GENERATE AC"),
    B5_b5("SCRIPT PROCESSING FAILED AFTER FINAL GENERATE AC"),
    B5_b4("RELAY RESISTANCE THRESHOLD EXCEEDED"),
    B5_b3("RELAY RESISTANCE TIME LIMITS EXCEEDED"),
    B5_b2("RFU"),
    B5_b1("RFU")
}